name: Auto-build artworks.json

on:
  push:
    paths:
      - "assets/**"
      - "thumbs/**"
      - "tools/build_artworks.py"
      - "server.py"

concurrency:
  group: autobuild-artworks
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-json:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (Pillow + Flask for server.py import)
        run: |
          python -m pip install --upgrade pip
          pip install pillow flask

      - name: Rebuild artworks.json
        run: |
          if [ -f tools/build_artworks.py ]; then
            python tools/build_artworks.py
          else
            python server.py --export-json
          fi

      - name: Commit changes (if any)
        run: |
          if ! git diff --quiet -- artworks.json thumbs; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add artworks.json thumbs
            git commit -m "CI: auto-rebuild artworks.json"
            git push
          else
            echo "No changes to commit."
          fi
