name: Build artworks.json & thumbs

on:
  push:
    paths:
      - "assets/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow flask

      - name: Build artworks.json (and thumbnails)
        run: |
          python server.py --export-json
          echo
          echo "=== Changed files ==="
          git status --porcelain || true

      - name: Commit changes (if any)
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add artworks.json thumbs/
            git commit -m "CI: rebuild artworks & thumbs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
